name: Stride MFP Sync
on:
  schedule:
    - cron: '30 3 * * *' # 4:30 AM GMT+1
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - setup-python: 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python Dependencies
        run: pip install -r sync/requirements.txt
      - name: Run Sync Script
        env:
          MFP_COOKIES: ${{ secrets.MFP_COOKIES }}
          MFP_USERNAME: ${{ secrets.MFP_USERNAME }}
        run: python sync/sync_mfp.py
      - name: Commit Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/stride-data.json
          git commit -m "Update MFP data" || echo "No changes"
          git push